# Generated by Django 4.2 on 2026-04-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cook_photos/')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cuisine_tags', models.CharField(blank=True, help_text='e.g. Bengali, North Indian, Chinese', max_length=255)),
                ('daily_capacity', models.PositiveIntegerField(default=20)),
                ('order_cutoff', models.TimeField(help_text='Time after which no more orders accepted')),
                ('same_day_enabled', models.BooleanField(default=False)),
                ('same_day_limit', models.PositiveIntegerField(default=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cook_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cook_profiles',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NONVEG', 'Non-Vegetarian'), ('EGG', 'Egg')], default='VEG', max_length=10)),
                ('spice_level', models.CharField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('SPICY', 'Spicy')], default='MEDIUM', max_length=10)),
                ('allergens', models.CharField(blank=True, help_text='e.g. nuts, dairy, gluten', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dish_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='cooks.cookprofile')),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 7-8 PM', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='cooks.cookprofile')),
            ],
            options={
                'db_table': 'delivery_slots',
                'ordering': ['start_time'],
                'unique_together': {('cook', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('order_cutoff', models.TimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='cooks.cookprofile')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='cooks.deliveryslot')),
            ],
            options={
                'db_table': 'daily_menus',
                'ordering': ['-menu_date', 'meal_type'],
                'unique_together': {('cook', 'menu_date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use dish base price', max_digits=8, null=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cooks.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cooks.dailymenu')),
            ],
            options={
                'db_table': 'menu_items',
                'unique_together': {('menu', 'dish')},
            },
        ),
    ]
