# Generated by Django 4.2 on 2026-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faileddelivery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='failed_deliveries/'),
        ),
    ]
