# Generated by Django 5.2.11 on 2026-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_fix_failed_delivery_photo_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible_to_cook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='visible_to_customer',
            field=models.BooleanField(default=True),
        ),
    ]
