# Generated by Django 4.2 on 2026-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PREPARING', 'Order Preparing'), ('ORDER_OUT', 'Out for Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_FAILED', 'Order Failed'), ('REVIEW_RECEIVED', 'Review Received'), ('INVOICE_CREATED', 'Invoice Created')], max_length=20),
        ),
    ]
